### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by ThatOneCalculator** [hadialqattan/no-darkreader#1]
![](https://cdn.discordapp.com/attachments/810799100940255260/955869669535907870/NoDarkReader.svg)

**Comment by hadialqattan** [comment]
Awesome, the new logo looks cool, kindly, open a PR that replaces the old logo with the new one under the same file name (`logo.png`).

I'm happy to see you around @ThatOneCalculator. 

Thank you for your contribution.

Have a good day!

**Comment by hadialqattan** [comment]
BTW, you can change the file format from `png` to `svg` but please don't forget to update the logo's path in the `README.md` file.

**Comment by ThatOneCalculator** [comment]
#2 :)
