### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by ghost** [hadialqattan/no-darkreader#4]
all you need to do is add `<meta name="darkreader-lock">` tag why make a plugin?

**Comment by hadialqattan** [comment]
> all you need to do is add `<meta name="darkreader-lock">` tag why make a plugin?

Hi @some11111 , this plugin has been created way before this feature exists!

Actually, I didn't notice the PR that adds this feature, so thanks a lot for letting me know about it. I'm gonna archive this repo ASAP.

**Comment by sandrock** [comment]
The [`darkreader` tag](https://github.com/darkreader/darkreader/issues/1114#issuecomment-661826455) does [not always fully disable dark reader](https://github.com/darkreader/darkreader/issues/4325#issuecomment-735976502). 

The [`darkreader-lock` tag](https://github.com/darkreader/darkreader/issues/4330) seems to work better.

I would wait ; )

**Comment by hadialqattan** [comment]
> The [`darkreader` tag](https://github.com/darkreader/darkreader/issues/1114#issuecomment-661826455) does [not always fully disable dark reader](https://github.com/darkreader/darkreader/issues/4325#issuecomment-735976502).
> 
> The [`darkreader-lock` tag](https://github.com/darkreader/darkreader/issues/4330) seems to work better.
> 
> I would wait ; )

Either way, the `darkreader-lock` tag has the exact purpose and functionality of this plugin so I have to deprecate this plugin!
